### ISSUE TITLE
ssh не работает, pi4/0.19img

### ISSUE THREAD

**Issue by whoim2** [CopterExpress/clover#234]
Распаковал на флешку, запустил, подрубился к wifi. SSH не отвечает на смартфоне и пк, вебморда отзывается только на смартфоне, на ПК ничего - даже не пингуется 1.11, адреса выданы верно, шлюз 1.11, адрес из этой подсети..
Подрубить пока нечего чтоб увидеть напрямую, hdmi монитора нет пока..
В чем может быть дело?

**Comment by okalachev** [comment]
Здравствуйте!

Каким образом вы подключаетесь по SSH?

Адрес RPi (и шлюз) в сети – 192.168.11.1, не 1.11.
