### ISSUE TITLE
Etcher flashing error with clover_v0.20.img

### ISSUE THREAD

**Issue by Jai-GAY** [CopterExpress/clover#240]
[Etcher 1.5.95](https://www.balena.io/etcher/) + [clover_v0.20.img](https://github.com/CopterExpress/clover/releases/tag/v0.20) = Checksum error [due to name change?]
[Etcher 1.5.95](https://www.balena.io/etcher/) + [clever_v0.18.img](https://github.com/CopterExpress/clover/releases/tag/v0.18) = No warning or error

![clover_v0 20_error](https://user-images.githubusercontent.com/12781023/83597953-18095480-a59b-11ea-9063-288ccc823f7c.jpg)

**Comment by okalachev** [comment]
I believe it might be a hardware problem, the image version has nothing with the checksum check.

Please, try to flash your SD card once again.

**Comment by Jai-GAY** [comment]
I had repeatedly flash, re-flash, SD card full format then flash, still, I get the error.

**Comment by okalachev** [comment]
Thanks for the report! We'll definitely investigate this issue more, and maybe even switch to advising Raspberry Pi Imager instead of Etcher.

We tested with Etcher 1.4.4 and had no problems.
