### ISSUE TITLE
ROS Melodic installation on Ubuntu

### ISSUE THREAD

**Issue by Jai-GAY** [CopterExpress/clover#242]
[Configure access keys in your system for correct download](https://clover.coex.tech/en/ros-install.html#ros-melodic-installation-on-ubuntu), this key is not working

sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

[this key works](http://wiki.ros.org/melodic/Installation/Ubuntu#Installation.2FUbuntu.2FSources.Set_up_your_keys)

sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

**Comment by sfalexrog** [comment]
Thank you for that! Looks like we've missed the ROS repository key change in the docs. Updated article should be up soon.
