### ISSUE TITLE
Why we need a Velocity estimation during automate flight?

### ISSUE THREAD

**Issue by kids0cn** [CopterExpress/clover#261]
I try to run an example program "flight.py", but it failed, it armed,but cannot takeoff。 Then I run the selfcheck.py, it tell me I need a 
velocity estimatiom, it's very hard to find this one in our contry。 Is it necessary for drone to fly?  you know, we have accelerator 。

**Comment by okalachev** [comment]
You need modified PX4 version for stable takeoff: https://clover.coex.tech/en/firmware.html. Do you use it?

Also, can you please provide the output of your `selfcheck.py` run?

**Comment by kids0cn** [comment]
Output  like this。
Firmware is the 1.10.0 stable

We cannot get the velocity estimation all the time and the local position sometimes。


`[WARN] [1596174460.936834]: FCU: not running Clover PX4 firmware, https://clover.coex.tech/firmware
[INFO] [1596174460.968883]: FCU: selected estimator: EKF2
[INFO] [1596174460.997979]: FCU: board rotation: no rotation
[INFO] [1596174462.683207]: IMU: OK
[WARN] [1596174463.725685]: Local position: no local position
[WARN] [1596174464.772381]: Velocity estimation: no velocity estimation
[INFO] [1596174464.963563]: Global position (GPS): OK
[INFO] [1596174465.061822]: Preflight status: OK
[WARN] [1596174466.097628]: Main camera: main_camera: no images (is the camera connected properly?)
[INFO] [1596174466.189875]: ArUco markers: aruco_detect is not running
[INFO] [1596174466.238043]: Simple offboard node: OK
[WARN] [1596174466.789452]: Optical flow: no optical flow data (from Raspberry)
[WARN] [1596174468.853867]: Vision position estimate: no VPE or MoCap messages
[INFO] [1596174469.237873]: Rangefinder: EKF2_HGT_MODE = Range sensor, operating over flat surface
[INFO] [1596174469.261750]: Rangefinder: EKF2_RNG_AID = 1, range sensor aiding enabled
[WARN] [1596174469.315333]: RPi health: system throttled to prevent damage
[WARN] [1596174469.327584]: RPi health: your system is susceptible to throttling
[WARN] [1596174469.338483]: RPi health: not enough power for onboard computer, flight inadvisable
[WARN] [1596174469.348658]: RPi health: power supply cannot provide enough power
[INFO] [1596174469.639233]: CPU usage: OK`


on the top of the informations,I get these:

`[INFO] [1596174459.502763]: Performing selfcheck...
[INFO] [1596174459.511667]: Image: version: v0.20
[INFO] [1596174459.521373]: Board: Raspberry Pi 3 Model B Plus Rev 1.3
[WARN] [1596174459.641568]: clover.service: ERROR: ros.cv_camera./main_camera: failed to open device... do nothing: device_path /dev/video0 cannot be opened
[WARN] [1596174459.652020]: clover.service: ERROR: ros.mavros.fcu: FCU: REJECT ALTITUDE CONTROL (7)
[WARN] [1596174459.661849]: clover.service: [ WARN] [1596172713.130567308]: ros.mavros.time: TM : RTT too high for timesync: 1612.09 ms.
[WARN] [1596174459.671535]: clover.service: [ WARN] [1596172713.135793819]: ros.mavros.time: TM : RTT too high for timesync: 1017.34 ms.
[WARN] [1596174459.682995]: clover.service: [ WARN] [1596172713.137202048]: ros.mavros.global_position: GP: No GPS fix
[WARN] [1596174459.692376]: clover.service: [ WARN] [1596172714.146018193]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174459.701600]: clover.service: ERROR: ros.mavros.fcu: FCU: REJECT POSITION CONTROL (39)
[WARN] [1596174459.710852]: clover.service: [ WARN] [1596172727.383688605]: ros.mavros.param: PR: request param #191 timeout, retries left 2, and 27 params still missing
[WARN] [1596174459.720429]: clover.service: [ WARN] [1596172743.947901307]: ros.mavros.global_position: GP: No GPS fix
[WARN] [1596174459.730144]: clover.service: [ WARN] [1596172752.939012762]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174459.739588]: clover.service: [ WARN] [1596172978.002053092]: ros.mavros.fcu: FCU: Preflight: GPS Horizontal Pos Drift too high
[WARN] [1596174459.748966]: clover.service: ERROR: ros.mavros.fcu: FCU: Arming denied! Press safety switch first (4)
[WARN] [1596174459.759217]: clover.service: ERROR: ros.mavros.fcu: FCU: Not arming: Preflight checks failed (4)
[WARN] [1596174459.769164]: clover.service: [ WARN] [1596172984.368013767]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174459.780406]: clover.service: ERROR: ros.mavros.fcu: FCU: No range data received, loitering. (18)
[WARN] [1596174459.790586]: clover.service: [ WARN] [1596172996.044470065]: ros.mavros.time: TM : RTT too high for timesync: 125.82 ms.
[WARN] [1596174459.800323]: clover.service: [ WARN] [1596173002.225821677]: ros.mavros.time: TM : RTT too high for timesync: 2107.24 ms.
[WARN] [1596174459.809572]: clover.service: [ WARN] [1596173002.230402510]: ros.mavros.time: TM : RTT too high for timesync: 1511.99 ms.
[WARN] [1596174459.818928]: clover.service: [ WARN] [1596173002.234038187]: ros.mavros.time: TM : RTT too high for timesync: 915.47 ms.
[WARN] [1596174459.829198]: clover.service: ERROR: ros.mavros.time: TM : Time jump detected. Resetting time synchroniser. (10)
[WARN] [1596174459.838777]: clover.service: [ WARN] [1596173040.779280152]: ros.mavros.fcu: FCU: Preflight: GPS Hor Speed Drift too high
[WARN] [1596174459.848265]: clover.service: [ WARN] [1596173042.316103849]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174459.858975]: clover.service: ERROR: ros.mavros.fcu: FCU: Autonomy off! Returned control to pilot (26)
[WARN] [1596174459.868593]: clover.service: [ WARN] [1596173060.079087645]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174459.877826]: clover.service: ERROR: ros.mavros.fcu: FCU: Failsafe enabled: no datalink (23)
[WARN] [1596174459.887688]: clover.service: [ WARN] [1596173072.036936442]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174459.896833]: clover.service: ERROR: ros.mavros.fcu: FCU: Collision Warning (12)
[WARN] [1596174459.906369]: clover.service: [ WARN] [1596173088.995235706]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174459.915512]: clover.service: [ WARN] [1596173140.180168499]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174459.926557]: clover.service: ERROR: ros.mavros.fcu: FCU: Low battery level! Return advised
[WARN] [1596174459.936079]: clover.service: [ WARN] [1596173200.656233216]: ros.mavros: CON: Lost connection, HEARTBEAT timed out.
[WARN] [1596174459.945271]: clover.service: [ WARN] [1596173205.139466600]: ros.mavros.time: TM : RTT too high for timesync: 1821.03 ms.
[WARN] [1596174459.956662]: clover.service: [ WARN] [1596173205.143821756]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174459.965783]: clover.service: [ WARN] [1596173205.147409672]: ros.mavros.time: TM : RTT too high for timesync: 1228.91 ms.
[WARN] [1596174459.975703]: clover.service: [ WARN] [1596173205.149693787]: ros.mavros.time: TM : RTT too high for timesync: 631.24 ms.
[WARN] [1596174459.985545]: clover.service: [ WARN] [1596173219.371765292]: ros.mavros.param: PR: request param #586 timeout, retries left 2, and 2 params still missing
[WARN] [1596174459.994959]: clover.service: [ WARN] [1596173243.854839085]: ros.mavros.cmd: CMD: Unexpected command 246, result 0
[WARN] [1596174460.004158]: clover.service: [ WARN] [1596173244.637233928]: ros.mavros.time: TM : RTT too high for timesync: 118.80 ms.
[WARN] [1596174460.015179]: clover.service: [ WARN] [1596173251.782267728]: ros.mavros: CON: Lost connection, HEARTBEAT timed out.
[WARN] [1596174460.026135]: clover.service: [ WARN] [1596173255.636454653]: ros.mavros.time: TM : RTT too high for timesync: 1918.01 ms.
[WARN] [1596174460.035983]: clover.service: [ WARN] [1596173255.643273612]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174460.045206]: clover.service: [ WARN] [1596173255.646602518]: ros.mavros.time: TM : RTT too high for timesync: 1328.17 ms.
[WARN] [1596174460.054946]: clover.service: [ WARN] [1596173255.651209184]: ros.mavros.time: TM : RTT too high for timesync: 732.75 ms.
[WARN] [1596174460.064060]: clover.service: [ WARN] [1596173269.852021575]: ros.mavros.param: PR: request param #686 timeout, retries left 2, and 1 params still missing
[WARN] [1596174460.074071]: clover.service: [ WARN] [1596173338.251023268]: ros.mavros: CON: Lost connection, HEARTBEAT timed out.
[WARN] [1596174460.084801]: clover.service: [ WARN] [1596173339.435258528]: ros.mavros.time: TM : RTT too high for timesync: 2116.84 ms.
[WARN] [1596174460.095062]: clover.service: [ WARN] [1596173339.445760559]: ros.mavros.time: TM : RTT too high for timesync: 1525.97 ms.
[WARN] [1596174460.104510]: clover.service: [ WARN] [1596173339.446935663]: ros.mavros.time: TM : RTT too high for timesync: 928.49 ms.
[WARN] [1596174460.114340]: clover.service: [ WARN] [1596173340.455488579]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174460.126164]: clover.service: [ WARN] [1596173353.649750762]: ros.mavros.param: PR: request param #248 timeout, retries left 2, and 5 params still missing
[WARN] [1596174460.137455]: clover.service: [ WARN] [1596173366.297241851]: ros.mavros.fcu: FCU: Preflight: GPS Hor Speed Drift too high
[WARN] [1596174460.147151]: clover.service: [ WARN] [1596173369.485075391]: ros.mavros.fcu: FCU: Preflight: GPS Hor Speed Drift too high
[WARN] [1596174460.156611]: clover.service: [ WARN] [1596173380.334852835]: ros.mavros.fcu: FCU: Preflight: GPS Horizontal Pos Drift too high
[WARN] [1596174460.167818]: clover.service: [ WARN] [1596173478.788319620]: ros.mavros: CON: Lost connection, HEARTBEAT timed out.
[WARN] [1596174460.178170]: clover.service: [ WARN] [1596173478.927202589]: ros.mavros.time: TM : RTT too high for timesync: 2108.66 ms.
[WARN] [1596174460.190737]: clover.service: [ WARN] [1596173478.938437953]: ros.mavros.time: TM : RTT too high for timesync: 1520.01 ms.
[WARN] [1596174460.200594]: clover.service: [ WARN] [1596173478.940595714]: ros.mavros.time: TM : RTT too high for timesync: 922.15 ms.
[WARN] [1596174460.210612]: clover.service: [ WARN] [1596173479.945800401]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174460.221327]: clover.service: [ WARN] [1596173493.160019615]: ros.mavros.param: PR: request param #136 timeout, retries left 2, and 2 params still missing
[WARN] [1596174460.234060]: clover.service: ERROR: ros.mavros.fcu: FCU: USB disconnected, rebooting. (3)
[WARN] [1596174460.244059]: clover.service: [ WARN] [1596173577.440654947]: ros.mavros.time: TM : RTT too high for timesync: 122.20 ms.
[WARN] [1596174460.253629]: clover.service: [ WARN] [1596173583.700731299]: ros.mavros.time: TM : RTT too high for timesync: 2182.31 ms.
[WARN] [1596174460.263178]: clover.service: [ WARN] [1596173583.704315049]: ros.mavros.time: TM : RTT too high for timesync: 1585.86 ms.
[WARN] [1596174460.273016]: clover.service: [ WARN] [1596173583.708296768]: ros.mavros.time: TM : RTT too high for timesync: 989.79 ms.
[WARN] [1596174460.285600]: clover.service: [ WARN] [1596173637.865504820]: ros.mavros.cmd: CMD: Unexpected command 246, result 0
[WARN] [1596174460.298398]: clover.service: [ WARN] [1596173638.657967788]: ros.mavros.time: TM : RTT too high for timesync: 139.53 ms.
[WARN] [1596174460.308893]: clover.service: [ WARN] [1596173645.058656640]: ros.mavros: CON: Lost connection, HEARTBEAT timed out.
[WARN] [1596174460.319154]: clover.service: [ WARN] [1596173649.838520128]: ros.mavros.time: TM : RTT too high for timesync: 2120.05 ms.
[WARN] [1596174460.330995]: clover.service: [ WARN] [1596173649.842776951]: ros.mavros.time: TM : RTT too high for timesync: 1523.94 ms.
[WARN] [1596174460.341531]: clover.service: [ WARN] [1596173649.845766690]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174460.351618]: clover.service: [ WARN] [1596173649.849231170]: ros.mavros.time: TM : RTT too high for timesync: 930.79 ms.
[WARN] [1596174460.361460]: clover.service: ERROR: ros.mavros.fcu: FCU: Dangerously low battery! Shutting system down
[WARN] [1596174460.370998]: clover.service: ERROR: ros.mavros.fcu: FCU: System does not support shutdown
[WARN] [1596174460.380762]: clover.service: [ WARN] [1596173748.278811392]: ros.mavros: CON: Lost connection, HEARTBEAT timed out.
[WARN] [1596174460.391098]: clover.service: [ WARN] [1596173753.925545869]: ros.mavros.time: TM : RTT too high for timesync: 2106.81 ms.
[WARN] [1596174460.401142]: clover.service: [ WARN] [1596173753.929292015]: ros.mavros.time: TM : RTT too high for timesync: 1510.88 ms.
[WARN] [1596174460.410819]: clover.service: [ WARN] [1596173753.932138942]: ros.mavros.time: TM : RTT too high for timesync: 913.62 ms.
[WARN] [1596174460.421733]: clover.service: [ WARN] [1596173754.945309411]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174460.432937]: clover.service: [ WARN] [1596173768.138067635]: ros.mavros.param: PR: request param #55 timeout, retries left 2, and 4 params still missing
[WARN] [1596174460.443766]: clover.service: [ WARN] [1596173967.295452767]: ros.mavros.time: TM : RTT too high for timesync: 176.99 ms.
[WARN] [1596174460.453513]: clover.service: ERROR: ros.mavros.fcu: FCU: Mag #0 fail:  TIMEOUT!
[WARN] [1596174460.462415]: clover.service: [ WARN] [1596173973.451971359]: ros.mavros.time: TM : RTT too high for timesync: 2033.47 ms.
[WARN] [1596174460.472314]: clover.service: [ WARN] [1596173973.455711359]: ros.mavros.time: TM : RTT too high for timesync: 1437.19 ms.
[WARN] [1596174460.482221]: clover.service: [ WARN] [1596173973.459360629]: ros.mavros.time: TM : RTT too high for timesync: 840.93 ms.
[WARN] [1596174460.492997]: clover.service: [ WARN] [1596174022.684333579]: ros.mavros.cmd: CMD: Unexpected command 520, result 0
[WARN] [1596174460.504560]: clover.service: [ WARN] [1596174096.688878916]: ros.mavros.time: TM : RTT too high for timesync: 170.42 ms.
[WARN] [1596174460.514086]: clover.service: [ WARN] [1596174102.825501049]: ros.mavros.time: TM : RTT too high for timesync: 2107.07 ms.
[WARN] [1596174460.525309]: clover.service: [ WARN] [1596174102.829978653]: ros.mavros.time: TM : RTT too high for timesync: 1511.53 ms.
[WARN] [1596174460.535469]: clover.service: [ WARN] [1596174102.834652038]: ros.mavros.time: TM : RTT too high for timesync: 916.20 ms.
[WARN] [1596174460.545503]: clover.service: [ WARN] [1596174138.254888171]: ros.mavros.fcu: FCU: Preflight: GPS Horizontal Pos Drift too high
[WARN] [1596174460.556262]: clover.service: [ WARN] [1596174150.645697749]: ros.mavros.fcu: FCU: Preflight: GPS Horizontal Pos Drift too high
[WARN] [1596174460.566783]: clover.service: [ WARN] [1596174157.344521757]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.578313]: clover.service: [ WARN] [1596174181.038030342]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.588793]: clover.service: [ WARN] [1596174195.660735649]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.598963]: clover.service: [ WARN] [1596174212.693412153]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.610330]: clover.service: [ WARN] [1596174242.881370683]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.621403]: clover.service: [ WARN] [1596174255.137885678]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.631561]: clover.service: [ WARN] [1596174266.947394997]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[WARN] [1596174460.640819]: clover.service: [ WARN] [1596174295.441343111]: ros.mavros.cmd: CMD: Unexpected command 176, result 0
[INFO] [1596174460.651342]: Network: OK
[ERROR] [1596174460.904442]: bad callback: <function mavlink_message_handler at 0x74038b30>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/pi/catkin_ws/src/clover/clover/src/selfcheck.py", line 115, in mavlink_message_handler
    mav_msg = link.decode(mav_bytes_msg)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/dialects/v10/ardupilotmega.py", line 12451, in decode
    raise MAVError('invalid MAVLink CRC in msgID %u 0x%04x should be 0x%04x' % (msgId, crc, crc2.crc))
MAVError: invalid MAVLink CRC in msgID 126 0x04c8 should be 0xed9c`

**Comment by okalachev** [comment]
The problem is that your FC doesn't obtain the local position of the drone. This happens due to incorrect configuration of the FC.

You can start with our fork of PX4 (https://clover.coex.tech/en/firmware.html) and our configuration guides.

Other problem is that the main camera connected to the RPi is not detected. You can troubleshoot it using our articles (https://clover.coex.tech/en/camera.html#troubleshooting).

Third problem is throttling of the RPi, which can be caused by not enough power to it.

**Comment by kids0cn** [comment]
Thank you for your help。 I have change the firmware  to your version。
When I run the selfcheck.py  everything  seems all right， I  got  "Local position"， I got "velocity esitimator" ，I got "main camerra working "，and the rangefinder。 and I can see the picture through  192.168.11.1:8080 optical flow debug page。

but when take off the drone。and change to "position"，the drone doesn't stay at the point, and will fly to anywhere randomly。

what should I do to fix the problem?

**Comment by okalachev** [comment]
Is camera orientation set correctly?

**Comment by kids0cn** [comment]
I set the camera  like what it looks like  in the handbook 。 Here is a picture, the camera towards the floor。Attached at the back of the drone。
![微信图片_20200804092550](https://user-images.githubusercontent.com/9114283/89242712-c92c7980-d634-11ea-963d-5e3faecc2323.jpg)

**Comment by kids0cn** [comment]
Hi, for using T265 camera, I change the system from Clover image to Ubuntu Mate 18.04 . How to do to make a clover.service?

**Comment by okalachev** [comment]
You should properly set the orientation of the camera (including the "yaw") like described here https://clover.coex.tech/en/camera_setup.html#frame.

**Comment by lupixi** [comment]
Hello, I used clover  4 kit with clover_v0.21.img and v1.8.2-clover.13 firmware, but it always "ERROR: ros.mavros.fcu: FCU: [lpe] vision position timeout". Could you please share about possible solutions for this problem? Since the drone was crazy flying while changing to simple offboard mode.

selfcheck.py information as follows:
![selfcheck_infor](https://user-images.githubusercontent.com/28702304/111056283-c215f580-84b8-11eb-9fd7-41ae30a6cc0b.jpg)

**Comment by okalachev** [comment]
Hi, answered in your e-mail. Please address Telegram support chat (https://t.me/COEXHelpdesk) for quicker help!
