### ISSUE TITLE
Hi I need some assistance can it work with ardupilot

### ISSUE THREAD

**Issue by CoderLogy** [CopterExpress/clover#296]
Pls tell me does it work with ardupilot

**Comment by okalachev** [comment]
Hi. We don't support ArduPilot specifically. This packages target PX4 primarily.

But some of the features (like getting telemetry and others) might work.

**Comment by CoderLogy** [comment]
So d u know something that would work with ardupilot like a service that u
made is there any service like same pls tell  pls tell me I need it

**Comment by okalachev** [comment]
Some of features will work. mavros package itself support Ardupilot, for example.

**Comment by CoderLogy** [comment]
Can u pls tel me how to program drone ardupilot with opencv rpi pls help me
