### ISSUE TITLE
Howto, whereto install coex gps sensor

### ISSUE THREAD

**Issue by Heavy02011** [CopterExpress/clover#298]
Any drawing, images, hints available?
apart from https://github.com/CopterExpress/clover/blob/master/docs/en/gps.md
thx!

**Comment by oponfil** [comment]
Hi! Not yet, unfortunately. But we will publish it in a couple of month.

**Comment by Heavy02011** [comment]
But please tell me at least whether the usb port would be needed / connected apart from the 4pin cable.
And would be really nice to get a photo of how you installed it in your prototype.
thx so much.

**Comment by oponfil** [comment]
You don't need a USB port. Just plug GPS to Pix using the 4pin cable.
