### ISSUE TITLE
VL530L0/1XV2 laser rangefinder not working

### ISSUE THREAD

**Issue by hahnpv** [CopterExpress/clover#389]
Good morning,

 I have the VL530L0/1XV2 laser rangefinder sensor wired up per the directions on https://clover.coex.tech/en/laser.html

 The particular model I am using is this: https://www.amazon.com/gp/product/B07Q5Y3G4C

 It is wired per the instructions and the Clover config file has it enabled, but the topic is not publishing messages.

 The device shows up when I perform an i2cdetect -y 1 with the expected address 0x29.

 How can I help debug this further?

 Thank you.

**Comment by okalachev** [comment]
Hi! 

Unfortunately, the only rangefinder supported by the installed driver is VL53L1X, not VL53L0X.
