### ISSUE TITLE
Can I use a clean Ubuntu image to make a control computer without downloading the img file?

### ISSUE THREAD

**Issue by yunswj** [CopterExpress/clover#428]
Can I use this library and make a record on the computer myself

**Comment by okalachev** [comment]
Yes, but it's not so easy to install everything required, that's why the ready image is made.

**Comment by okalachev** [comment]
You can take some info in the simulator installation manual (https://clover.coex.tech/en/simulation_native.html), which is kind of a superset of the required software.

**Comment by yunswj** [comment]
Your response speed is too fast, awesome! ! ! I just want to study the implementation of clover Python package in from clover import srv

**Comment by okalachev** [comment]
There is no separate Clover Python library, the Python modules are generated by ROS while package building (from .srv and .msg files). Programs for Clover use `rospy` library to access Clover services and topics.

**Comment by yunswj** [comment]
Let me study the .srv and .msg files of ROS. thank you for your reply
