### ISSUE TITLE
Undefined substitution argument visual_material 

### ISSUE THREAD

**Issue by iamrajee** [CopterExpress/clover#433]
I'm getting the below error while running `roslaunch clover_simulation simulator.launch`. I was following [this](https://clover.coex.tech/en/simulation_native.html) tutorial.

rajendra@u20:~/drone_ws$ roslaunch clover_simulation simulator.launch
... logging to /home/rajendra/.ros/log/d8dbb14c-8caa-11ec-81f3-f39e9237e8e2/roslaunch-u20-672293.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Undefined substitution argument visual_material 
when evaluating expression 'color'
when instantiating macro: vertical_clover_rotor (/home/rajendra/drone_ws/src/clover/clover_description/urdf/clover/clover4_macros.xacro)
in file: /home/rajendra/drone_ws/src/clover/clover_description/urdf/clover/clover4_physics.xacro
included from: /home/rajendra/drone_ws/src/clover/clover_description/urdf/clover/clover4_base.xacro
included from: /home/rajendra/drone_ws/src/clover/clover_description/urdf/clover/clover4.xacro
RLException: while processing /home/rajendra/drone_ws/src/clover/clover_description/launch/spawn_drone.launch:
Invalid <param> tag: Cannot load command parameter [drone_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '/home/rajendra/drone_ws/src/clover/clover_description/urdf/clover/clover4.xacro', 'main_camera:=true', 'rangefinder:=true', 'led:=true', 'gps:=false', 'maintain_camera_rate:=false', 'use_clover_physics:=false']] returned with code [2]. 

Param xml is <param command="$(arg cmd)" name="drone_description"/>
The traceback for the exception was written to the log file

**Comment by okalachev** [comment]
Hi! I guess this might be related to this change: https://github.com/CopterExpress/clover/commit/b6bd6bdde8c10c732d6a536d139df0310ea9fc0e#diff-1053df277d01eecbc3dd9b738996bfd1475aedea2dc5552bd8608c644f946bb0L25.

I don't understand how it works everywhere, including our image, though.

Try to just replace `$(arg visual_material)` to `DarkGrey` in `clover4_physics.xacro`.

**Comment by iamrajee** [comment]
@okalachev Thank you so much for your prompt response. I would try your suggestion and would update back :)

**Comment by okalachev** [comment]
@iamrajee, hi, have you found some time to test the fix, so I could commit it?

**Comment by iamrajee** [comment]
> @iamrajee, hi, have you found some time to test the fix, so I could commit it?

No, I just tried replacing `$(arg visual_material)` with `DarkGreyDarkGrey`, and it worked. Haven't tried anything else.

**Comment by okalachev** [comment]
You mean, in fact, you successfully tested this patch, but only with `DarkGreyDarkGrey` instead of `DarkGrey`?

**Comment by okalachev** [comment]
Considering the fix works, so committed. @iamrajee, thanks for the report.
