### ISSUE TITLE
Question about the convertion from xacro files to urdf files

### ISSUE THREAD

**Issue by ge35tay** [CopterExpress/clover#436]
Hello, i have a problem regarding the xacro files. I try to convert the xacro files in clover_description to urdf files,  but the convertion of files: clover4_physics.xacro and clover4_base.xacro always fail:  "Undefined substitution argument use_clover_physics". Could u tell why?

I know it maybe a very basic question but i am new to ros so this is very strange for me. Thanks in advance

**Comment by okalachev** [comment]
Hi! The purpose of using xacro is to parametrize URDF files. So we can use the drone with or without the camera, with or without the gps, etc. These xacro parameters are arguments, which you didn't provide for the converter.

Also you should not use `clover4_*.xacro`, these files are included to the main entry file, `clover4.xacro`. When the Clover sim runs, it uses the main file, and passes the parameters to it.

See: https://github.com/CopterExpress/clover/blob/master/clover_description/launch/spawn_drone.launch#L14.
