### ISSUE TITLE
Report error with "TRANSITION_DENIED: SHUTDOWN to INIT" while calibrating sensors in Pixhawk

### ISSUE THREAD

**Issue by phtchpol** [CopterExpress/clover#442]
Hi, I encountered a problem while calibrating sensor for Pixhawk. The system told me that it failed to switch state from shutdown to init even though the system doesn't allow shutdown during when Pixhawk plugged into PC via USB.
![Calibration Error](https://user-images.githubusercontent.com/78231132/170819451-e67f9496-50dd-4837-aae9-e6bd6818aba1.png)

**Comment by okalachev** [comment]
Can you try to perform the calibration with external power from battery? This might solve the issue.

**Comment by phtchpol** [comment]
The problem still persist. Might be from outdated firmware with outdated hardware. I will try to reflash firmware again

**Comment by phtchpol** [comment]
The problem solve after flashing new firmware into more up-to-dated hardware. Thank you

**Comment by Jai-GAY** [comment]
> The problem solve after flashing new firmware into more up-to-dated hardware. Thank you

May I know [which version](https://github.com/CopterExpress/Firmware/tags) did you use? I faced the same issue.
