### ISSUE TITLE
ArUco_detector not publishing the detected marker array

### ISSUE THREAD

**Issue by VL69** [CopterExpress/clover#444]
When I launch the marker detector with my own virtual camera placed in a Gazebo environment, it is nog apple to publish the detected markers to the MarkerArray topic and gives following error when trying to look at the published topic via RQT
TopicInfo.__init__(): topic "/aruco_map/markers": can not get message class for type "aruco_pose/MarkerArray"

I was trying to send a camera matrix via the camera_info topic that includes some errors, but now the detector does not even work when just subscribing to the correct imag and camera info topic

**Comment by okalachev** [comment]
If your rqt says, that there is no message class for `aruco_pose/MarkerArray`, then it means that `aruco_pose` is not properly installed on this system.

You can check it using the following command:

```bash
rosmsg show aruco_pose/MarkerArray
```

**Comment by VL69** [comment]
Thank you for your answer, but when i type in this command it it shows:
Unable to load msg [aruco_pose/MarkerArray]: Cannot locate message [MarkerArray]: unknown package [aruco_pose] on search path [{'filters': ['/opt/ros/noetic/share/filters/msg']
and then continues to list every other message type that I have installed.
I was able to run the code and detect the markers untill wednesday, so i wouldn't think it has anything to do with an incorrect installation.
TIA

**Comment by okalachev** [comment]
Maybe you haven't sourced the `setup.bash` of the workspace, where you have built `aruco_pose` package. Something like:

```bash
source ~/catkin_ws/devel/setup.bash
```

**Comment by VL69** [comment]
The terminal has already been sourced, and I would like to thank you for your answer, but i think the problem is a little more complicated

**Comment by okalachev** [comment]
What was the method of installation of `aruco_pose` package you used? Try to rebuild/reinstall it.

**Comment by VL69** [comment]
The installation is working, I am also able to detect the markers and view the image of the camera with the overlayed lines for detected markers. The only problem is that the aruco_pose/MarkerArray message is not published to its topic, and i need the poses of the detected markers for further processing.

**Comment by okalachev** [comment]
rqt not having access to `aruco_pose/MarkerArray` type class and the topic `/aruco_detect/markers` not publishing are **different** issues.

Have you fixed your `aruco_pose/MarkerArray` type class issue?

You also can check the topic with `rostopic` tool:

```bash
rostopic echo /aruco_detect/markers
```

Note also, that to estimate the marker poses you have to:

* Provide correct camera calibration with `camera_info` topic.
* Set correct markers length in the `/aruco_detect/length` parameter.

**Comment by VL69** [comment]
All parameters were set up correctly, The problem appeared on its own and now without changing anything while searching a different solution, it started working again. Thanks for the help, I still have no idea what caused the problem. It looked like the camera info stream just stopped and know it works again.
