### ISSUE TITLE
When roslaunch clover_simulation simulation.launch is run it does not spawn the gazebo urdf model

### ISSUE THREAD

**Issue by AvishkarSeth** [CopterExpress/clover#446]
Error message: [WARN] [1656980174.968365, 0.000000]: wait_for_service(/gazebo/spawn_urdf_model): failed to contact, will keep trying
![Screenshot from 2022-07-05 10-20-37](https://user-images.githubusercontent.com/46049792/177227859-34ff549b-9c12-4d1d-9081-c0f061aed58f.png)

**Comment by okalachev** [comment]
Hi, which method have you used to install the simulator?

**Comment by AvishkarSeth** [comment]
> Hi, which method have you used to install the simulator?

The one in this link...
https://clover.coex.tech/en/simulation_native.html

**Comment by okalachev** [comment]
Do I understand correctly the problem is that the drone doesn't appear? The warning you provided may be not the cause of it. Maybe some other errors in the output?

`/gazebo/spawn_urdf_model` service takes some time to appear, by the service caller would wait for it.

**Comment by AvishkarSeth** [comment]
![Screenshot from 2022-07-05 11-56-48](https://user-images.githubusercontent.com/46049792/177234587-be84e31f-3716-4493-8b4e-08c681db7053.png)
As per the screenshots I attached... the simulator does not launch the gazebo model and also the examples such as 'flight.py' do not work. I tried reinstalling everything thrice but same issue

**Comment by okalachev** [comment]
This is only the little ending part of the output log. Can you please provide the full log? There can be errors there.

**Comment by AvishkarSeth** [comment]
buntu:~/catkin_ws/src/clover/clover/examples$ roslaunch clover_simulation simulator.launch 
... logging to /home/alice/.ros/log/9a926538-fc09-11ec-abfe-6974411158b9/roslaunch-SCI-10657-Ubuntu-30850.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://127.0.1.1:33591/

SUMMARY
========

CLEAR PARAMETERS
 * /led/led_effect/
 * /main_camera_nodelet_manager/
 * /mavros/
 * /optical_flow/
 * /roswww_static/
 * /simple_offboard/
 * /vpe_publisher/

PARAMETERS
 * /drone_description: <?xml version="1....
 * /gazebo/enable_ros_network: True
 * /led/led_effect/blink_rate: 2
 * /led/led_effect/fade_period: 0.5
 * /led/led_effect/notify/acro/b: 0
 * /led/led_effect/notify/acro/g: 155
 * /led/led_effect/notify/acro/r: 245
 * /led/led_effect/notify/altctl/b: 40
 * /led/led_effect/notify/altctl/g: 255
 * /led/led_effect/notify/altctl/r: 255
 * /led/led_effect/notify/connected/effect: rainbow
 * /led/led_effect/notify/disconnected/b: 50
 * /led/led_effect/notify/disconnected/effect: blink
 * /led/led_effect/notify/disconnected/g: 50
 * /led/led_effect/notify/disconnected/r: 255
 * /led/led_effect/notify/error/b: 0
 * /led/led_effect/notify/error/effect: flash
 * /led/led_effect/notify/error/g: 0
 * /led/led_effect/notify/error/ignore: ['[lpe] vision po...
 * /led/led_effect/notify/error/r: 255
 * /led/led_effect/notify/low_battery/b: 0
 * /led/led_effect/notify/low_battery/effect: blink_fast
 * /led/led_effect/notify/low_battery/g: 0
 * /led/led_effect/notify/low_battery/r: 255
 * /led/led_effect/notify/low_battery/threshold: 3.6
 * /led/led_effect/notify/offboard/b: 250
 * /led/led_effect/notify/offboard/g: 20
 * /led/led_effect/notify/offboard/r: 220
 * /led/led_effect/notify/posctl/b: 220
 * /led/led_effect/notify/posctl/g: 100
 * /led/led_effect/notify/posctl/r: 50
 * /led/led_effect/notify/stabilized/b: 50
 * /led/led_effect/notify/stabilized/g: 180
 * /led/led_effect/notify/stabilized/r: 30
 * /led/led_effect/notify/startup/b: 255
 * /led/led_effect/notify/startup/g: 255
 * /led/led_effect/notify/startup/r: 255
 * /led/led_effect/rainbow_period: 5
 * /main_camera/main_camera_markers/scale: 3.0
 * /main_camera_nodelet_manager/num_worker_threads: 2
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 8
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/rangefinder/field_of_view: 0.5
 * /mavros/distance_sensor/rangefinder/frame_id: rangefinder
 * /mavros/distance_sensor/rangefinder/id: 0
 * /mavros/distance_sensor/rangefinder/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/covariance: 1
 * /mavros/distance_sensor/rangefinder_sub/id: 1
 * /mavros/distance_sensor/rangefinder_sub/orientation: PITCH_270
 * /mavros/distance_sensor/rangefinder_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_url: udp://@127.0.0.1:...
 * /mavros/gcs_quiet_mode: True
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/imu/angular_velocity_stdev: 0.000349065850398...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/send: True
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/in/child_frame_id: base_link
 * /mavros/odometry/in/frame_id: odom
 * /mavros/odometry/in/frame_tf/body_frame_orientation: flu
 * /mavros/odometry/in/frame_tf/local_frame: local_origin_ned
 * /mavros/odometry/out/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/out/frame_tf/local_frame: vision_ned
 * /mavros/plugin_whitelist: ['altitude', 'com...
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.11868238913561441
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: True
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: False
 * /mavros/target_system_id: 1
 * /mavros/time/publish_sim_time: False
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /optical_flow/calc_flow_gyro: True
 * /optical_flow/roi_rad: 0.8
 * /rangefinder/range/covariance: 1
 * /rangefinder/range/id: 1
 * /rangefinder/range/orientation: PITCH_270
 * /rangefinder/range/subscriber: True
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 0.0.0.0
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/bson_only_mode: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 10
 * /rosbridge_websocket/use_compression: False
 * /rosbridge_websocket/websocket_external_port: None
 * /rosbridge_websocket/websocket_ping_interval: 0
 * /rosbridge_websocket/websocket_ping_timeout: 30
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /roswww_static/default_package: clover
 * /simple_offboard/reference_frames/main_camera_optical: map
 * /use_sim_time: True
 * /visualization/child_frame_id: base_link
 * /visualization/fixed_frame_id: map
 * /visualization/marker_scale: 1
 * /visualization/max_track_size: 20
 * /visualization/num_rotors: 4
 * /vpe_publisher/force_init: True
 * /vpe_publisher/offset_frame_id: aruco_map
 * /web_video_server/default_stream_type: ros_compressed
 * /web_video_server/publish_rate: 1.0

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    main_camera_frame (tf2_ros/static_transform_publisher)
    main_camera_nodelet_manager (nodelet/nodelet)
    map_flipped_frame (tf2_ros/static_transform_publisher)
    mavros (mavros/mavros_node)
    optical_flow (nodelet/nodelet)
    rangefinder_frame (tf2_ros/static_transform_publisher)
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)
    roswww_static (roswww_static/main.py)
    simple_offboard (clover/simple_offboard)
    sitl_0 (px4/px4)
    spawn_SCI_10657_Ubuntu_30850_459058826786188640 (gazebo_ros/spawn_model)
    tf2_web_republisher (tf2_web_republisher/tf2_web_republisher)
    visualization (mavros_extras/visualization)
    vpe_publisher (clover/vpe_publisher)
    web_video_server (web_video_server/web_video_server)
  /led/
    led_effect (clover/led)
  /main_camera/
    main_camera_markers (clover/camera_markers)

auto-starting new master
process[master]: started with pid [30860]
ROS_MASTER_URI=http://127.0.1.1:11311

setting /run_id to 9a926538-fc09-11ec-abfe-6974411158b9
process[rosout-1]: started with pid [30870]
started core service [/rosout]
process[gazebo-2]: started with pid [30878]
process[gazebo_gui-3]: started with pid [30882]
process[sitl_0-4]: started with pid [30892]
INFO  [px4] Creating symlink /home/alice/catkin_ws/src/PX4-Autopilot/ROMFS/px4fmu_common -> /home/alice/.ros/etc

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
Info: found model autostart file as SYS_AUTOSTART=4500
process[spawn_SCI_10657_Ubuntu_30850_459058826786188640-5]: started with pid [30905]
INFO  [param] selected parameter default file eeprom/parameters_4500
INFO  [parameters] BSON document size 465 bytes, decoded 465 bytes
[param] Loaded: eeprom/parameters_4500
process[mavros-6]: started with pid [30912]
process[rangefinder_frame-7]: started with pid [30920]
process[visualization-8]: started with pid [30944]
process[web_video_server-9]: started with pid [31000]
process[vpe_publisher-10]: started with pid [31016]
process[optical_flow-11]: started with pid [31028]
process[map_flipped_frame-12]: started with pid [31037]
process[simple_offboard-13]: started with pid [31050]
process[main_camera_frame-14]: started with pid [31058]
[ INFO] [1656987872.884285591]: ros.clover: using data topic
process[main_camera_nodelet_manager-15]: started with pid [31073]
process[main_camera/main_camera_markers-16]: started with pid [31083]
[ INFO] [1656987872.897007407]: ros.nodelet: Loading nodelet /optical_flow of type clover/optical_flow to manager main_camera_nodelet_manager with the following remappings:
process[rosbridge_websocket-17]: started with pid [31097]
[ INFO] [1656987872.901627246]: ros.nodelet: /camera_info -> /main_camera/camera_info
[ INFO] [1656987872.901666136]: ros.nodelet: /image_raw -> /main_camera/image_raw
process[rosapi-18]: started with pid [31103]
process[tf2_web_republisher-19]: started with pid [31111]
[ INFO] [1656987872.913930355]: ros.roscpp: waitForService: Service [/main_camera_nodelet_manager/load_nodelet] has not been advertised, waiting...
process[led/led_effect-20]: started with pid [31119]
process[roswww_static-21]: started with pid [31123]
[ INFO] [1656987872.924786587]: ros.clover: ready
[ INFO] [1656987872.925687780]: ros.mavros: FCU URL: udp://@127.0.0.1:14580
[ INFO] [1656987872.933417298]: ros.rosconsole_bridge.mavconn: udp0: Bind address: 0.0.0.0:14555
[ INFO] [1656987872.933480744]: ros.rosconsole_bridge.mavconn: udp0: Remote address: 127.0.0.1:14580
[ INFO] [1656987872.933527503]: ros.mavros: GCS bridge disabled
[ INFO] [1656987872.943090525]: ros.mavros: Plugin 3dr_radio blacklisted
[ INFO] [1656987872.943113302]: ros.mavros: Plugin actuator_control blacklisted
[ INFO] [1656987872.943126661]: ros.mavros: Plugin adsb blacklisted
[ INFO] [1656987872.948248615]: ros.mavros: Plugin altitude loaded
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
[ INFO] [1656987872.950676671]: ros.nodelet: Initializing nodelet with 2 worker threads.
PX4 SIM HOST: localhost
[ INFO] [1656987872.951443289]: ros.mavros: Plugin altitude initialized
[ INFO] [1656987872.951469567]: ros.mavros: Plugin cam_imu_sync blacklisted
[ INFO] [1656987872.951484798]: ros.mavros: Plugin camera blacklisted
[ INFO] [1656987872.951538621]: ros.mavros: Plugin command loaded
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
[ INFO] [1656987872.962070352]: ros.roscpp: waitForService: Service [/led/set_leds] has not been advertised, waiting...
[ INFO] [1656987872.971011849]: ros.mavros: Plugin command initialized
[ INFO] [1656987872.971052328]: ros.mavros: Plugin companion_process_status blacklisted
[ INFO] [1656987872.971067582]: ros.mavros: Plugin debug_value blacklisted
[ INFO] [1656987872.973891618]: ros.mavros: Plugin distance_sensor loaded
[ INFO] [1656987872.984763053]: ros.mavros: Plugin distance_sensor initialized
[ INFO] [1656987872.984790544]: ros.mavros: Plugin esc_status blacklisted
[ INFO] [1656987872.984804047]: ros.mavros: Plugin esc_telemetry blacklisted
[ INFO] [1656987872.984815764]: ros.mavros: Plugin fake_gps blacklisted
[ INFO] [1656987872.984882166]: ros.mavros: Plugin ftp loaded
[ INFO] [1656987872.992946059]: ros.mavros: Plugin ftp initialized
[ INFO] [1656987872.992973620]: ros.mavros: Plugin geofence blacklisted
[ INFO] [1656987872.993038775]: ros.mavros: Plugin global_position loaded
[ INFO] [1656987872.997286046]: ros.clover: ready
[ INFO] [1656987873.002984957]: ros.mavros: Plugin global_position initialized
[ INFO] [1656987873.003019024]: ros.mavros: Plugin gps_input blacklisted
[ INFO] [1656987873.003032652]: ros.mavros: Plugin gps_rtk blacklisted
[ INFO] [1656987873.003045700]: ros.mavros: Plugin gps_status blacklisted
[ INFO] [1656987873.003059856]: ros.mavros: Plugin hil blacklisted
[ INFO] [1656987873.003074243]: ros.mavros: Plugin home_position blacklisted
[ INFO] [1656987873.003140604]: ros.mavros: Plugin imu loaded
[ INFO] [1656987873.006818252]: ros.mavros: Plugin imu initialized
[ INFO] [1656987873.006849286]: ros.mavros: Plugin landing_target blacklisted
[ INFO] [1656987873.006913777]: ros.mavros: Plugin local_position loaded
[ INFO] [1656987873.009518662]: ros.mavros: Plugin local_position initialized
[ INFO] [1656987873.009550425]: ros.mavros: Plugin log_transfer blacklisted
[ INFO] [1656987873.009565464]: ros.mavros: Plugin mag_calibration_status blacklisted
[ INFO] [1656987873.009628168]: ros.mavros: Plugin manual_control loaded
[ INFO] [1656987873.010886279]: ros.mavros: Plugin manual_control initialized
[ INFO] [1656987873.010907041]: ros.mavros: Plugin mocap_pose_estimate blacklisted
[ INFO] [1656987873.010921763]: ros.mavros: Plugin mount_control blacklisted
[ INFO] [1656987873.010937897]: ros.mavros: Plugin nav_controller_output blacklisted
[ INFO] [1656987873.010951543]: ros.mavros: Plugin obstacle_distance blacklisted
[ INFO] [1656987873.010964420]: ros.mavros: Plugin odom blacklisted
[ INFO] [1656987873.010977207]: ros.mavros: Plugin onboard_computer_status blacklisted
[ INFO] [1656987873.011032636]: ros.mavros: Plugin param loaded
[ INFO] [1656987873.012266979]: ros.mavros: Plugin param initialized
[ INFO] [1656987873.012288199]: ros.mavros: Plugin play_tune blacklisted
[ INFO] [1656987873.012337619]: ros.mavros: Plugin px4flow loaded
[ INFO] [1656987873.015286531]: ros.mavros: Plugin px4flow initialized
[ INFO] [1656987873.015315678]: ros.mavros: Plugin rallypoint blacklisted
[ INFO] [1656987873.015331016]: ros.mavros: Plugin rangefinder blacklisted
[ INFO] [1656987873.015386981]: ros.mavros: Plugin rc_io loaded
[ INFO] [1656987873.017086509]: ros.mavros: Plugin rc_io initialized
[ INFO] [1656987873.017111214]: ros.mavros: Plugin safety_area blacklisted
[ INFO] [1656987873.017126174]: ros.mavros: Plugin setpoint_accel blacklisted
[ INFO] [1656987873.017220829]: ros.mavros: Plugin setpoint_attitude loaded
[ INFO] [1656987873.022244177]: ros.mavros: Plugin setpoint_attitude initialized
[ INFO] [1656987873.022324263]: ros.mavros: Plugin setpoint_position loaded
[ INFO] [1656987873.032257767]: ros.mavros: Plugin setpoint_position initialized
[ INFO] [1656987873.032341840]: ros.mavros: Plugin setpoint_raw loaded
[ INFO] [1656987873.039688087]: ros.mavros: Plugin setpoint_raw initialized
[ INFO] [1656987873.039717535]: ros.mavros: Plugin setpoint_trajectory blacklisted
[ INFO] [1656987873.039784186]: ros.mavros: Plugin setpoint_velocity loaded
[ INFO] [1656987873.042233622]: ros.mavros: Plugin setpoint_velocity initialized
[ INFO] [1656987873.042314359]: ros.mavros: Plugin sys_status loaded
[ INFO] [1656987873.047119124]: ros.mavros: Plugin sys_status initialized
[ INFO] [1656987873.047195233]: ros.mavros: Plugin sys_time loaded
[ INFO] [1656987873.049786401]: ros.mavros.time: TM: Timesync mode: MAVLINK
[ INFO] [1656987873.050136994]: ros.mavros.time: TM: Not publishing sim time
[ INFO] [1656987873.050701761]: ros.mavros: Plugin sys_time initialized
[ INFO] [1656987873.050723254]: ros.mavros: Plugin terrain blacklisted
[ INFO] [1656987873.050736218]: ros.mavros: Plugin trajectory blacklisted
[ INFO] [1656987873.050750748]: ros.mavros: Plugin tunnel blacklisted
[ INFO] [1656987873.050765541]: ros.mavros: Plugin vfr_hud blacklisted
[ INFO] [1656987873.050778637]: ros.mavros: Plugin vibration blacklisted
[ INFO] [1656987873.050836088]: ros.mavros: Plugin vision_pose_estimate loaded
[ INFO] [1656987873.053937847]: ros.mavros: Plugin vision_pose_estimate initialized
[ INFO] [1656987873.053970079]: ros.mavros: Plugin vision_speed_estimate blacklisted
[ INFO] [1656987873.053987045]: ros.mavros: Plugin waypoint blacklisted
[ INFO] [1656987873.054000722]: ros.mavros: Plugin wheel_odometry blacklisted
[ INFO] [1656987873.054014230]: ros.mavros: Plugin wind_estimation blacklisted
[ INFO] [1656987873.054068497]: ros.mavros: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1656987873.054085686]: ros.mavros: Built-in MAVLink package version: 2022.3.3
[ INFO] [1656987873.054106481]: ros.mavros: Known MAVLink dialects: common ardupilotmega ASLUAV AVSSUAS all development icarous matrixpilot paparazzi standard storm32 uAvionix ualberta
[ INFO] [1656987873.054126714]: ros.mavros: MAVROS started. MY ID 1.240, TARGET ID 1.1
Gazebo multi-robot simulator, version 11.11.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Wrn] [GuiIface.cc:200] g/gui-plugin is really loading a SystemPlugin. To load a GUI plugin please use --gui-client-plugin 
Gazebo multi-robot simulator, version 11.11.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

2022-07-05 12:24:33+1000 [-] Log opened.
2022-07-05 12:24:33+1000 [-] registered capabilities (classes):
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.call_service.CallService'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.advertise.Advertise'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.publish.Publish'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.subscribe.Subscribe'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.advertise_service.AdvertiseService'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.service_response.ServiceResponse'>
2022-07-05 12:24:33+1000 [-]  - <class 'rosbridge_library.capabilities.unadvertise_service.UnadvertiseService'>
[ INFO] [1656987873.240350078]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1656987873.241279235]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[INFO] [1656987873.246844, 0.000000]: Loading model XML from ros parameter drone_description
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.0.0.18
[INFO] [1656987873.252253, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1656987873.299666, 0.000000]: rosout: Rosapi started
[ INFO] [1656987873.341348733]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1656987873.342088895]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.0.0.18
2022-07-05 12:24:33+1000 [-] WebSocketServerFactory starting on 9090
2022-07-05 12:24:33+1000 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7f0579e43a00>
2022-07-05 12:24:33+1000 [-] [INFO] [1656987873.353621, 0.000000]: rosout: Rosbridge WebSocket server started at ws://0.0.0.0:9090
[Msg] Loading world file [/home/alice/catkin_ws/src/clover/clover_simulation/resources/worlds/clover_aruco.world]
[roswww_static-21] process has finished cleanly
log file: /home/alice/.ros/log/9a926538-fc09-11ec-abfe-6974411158b9/roswww_static-21*.log
[WARN] [1656987874.155939, 0.000000]: wait_for_service(/gazebo/spawn_urdf_model): failed to contact, will keep trying




Ubuntu:~/catkin_ws/src/clover/clover/examples$ python3 flight.py
Take off and hover 1 m above the ground
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 567, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 509, in call
    transport.connect(dest_addr, dest_port, service_uri)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 596, in connect
    raise TransportInitError(str(e)) #re-raise i/o error
rospy.exceptions.TransportInitError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flight.py", line 19, in <module>
    navigate(x=0, y=0, z=1, frame_id='body', auto_arm=True)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: [Errno 111] Connection refused

**Comment by okalachev** [comment]
Maybe some networking issues?

Can this machine ping itself? Do other ROS tools work, while the sim is running? (`rostopic list`, `rosservice list`, `rostopic echo <any-topic>`, etc. 

What is the output of `rosservice list`?

**Comment by AvishkarSeth** [comment]
![Screenshot from 2022-07-05 12-59-19](https://user-images.githubusercontent.com/46049792/177240884-99b75324-465f-4eee-9ba9-858c6a2ac046.png)
Would this help?

**Comment by okalachev** [comment]
What about the list of services (`rosservice list`) and other stuff, when the sim is running? Note, you don't have to run `roscore` yourself, roslaunch will do this.

**Comment by AvishkarSeth** [comment]
Hi Okalachev,
![Screenshot from 2022-07-06 09-45-10](https://user-images.githubusercontent.com/46049792/177434958-1588f564-feba-4d2e-9494-b579c341c0f3.png)
![Screenshot from 2022-07-06 09-51-40](https://user-images.githubusercontent.com/46049792/177435096-bed2943e-0057-4c56-b1a2-6200266f5774.png)


In the 'simulator.launch' file, what model is it calling? Is it 'clover.launch'? And maybe the file in the git repo is named 'clover4.launch' or something? I'm not sure...

**Comment by AvishkarSeth** [comment]
Hi Okalachev,

These two links helped resolve the issue!
1. https://answers.gazebosim.org//question/21602/spawning-baxterurdf-not-possible-gazebo-doesnt-start-waiting-for-service/
2. https://forum.humanbrainproject.eu/t/waiting-for-service-gazebo-spawn-urdf-model/468
Thanks for the help!

**Comment by okalachev** [comment]
Great!
