### ISSUE TITLE
Mavros cannot connect to Pixhawk 6C

### ISSUE THREAD

**Issue by Kiencate** [CopterExpress/clover#483]
I have just purchased a Pixhawk 6C flight controller. I have connected it to a Raspberry Pi 4 using Clover image via USB. The Pi 4 recognizes the USB device, but mavros is not able to retrieve any information from the Pixhawk. Additionally, I am unable to connect to it via QGround.

**Comment by okalachev** [comment]
Hi!

By default, mavros is configured the way so it connects to the file `/dev/px4fmu`, which is created by udev using the rules: https://github.com/CopterExpress/clover/blob/master/clover/udev/99-px4fmu.rules. It's done to avoid connection to some random connected USB devices.

You can either [change `mavros.launch`](https://github.com/CopterExpress/clover/blob/master/clover/launch/mavros.launch#L9) to simply connect to `/dev/ttyACM0`, or add an appropriate rule to the rules file (you can send it as a PR also).
