### ISSUE TITLE
RLException

### ISSUE THREAD

**Issue by shourez** [CopterExpress/clover#486]
Trying to follow https://clover.coex.tech/en/simulation_native.html on a PC with Intel i7

after

roslaunch clover_simulation simulator.launch

receive this terminal output

designer@designer-B365M-DS3H:~$ roslaunch clover_simulation simulator.launch
RLException: [simulator.launch] is neither a launch file in package [clover_simulation] nor is [clover_simulation] a launch file name
The traceback for the exception was written to the log file

**Comment by okalachev** [comment]
Are you sure you have sourced the workspace's `setup.bash` file (`source ~/catkin_ws/devel/setup.bash`)?
