### ISSUE TITLE
Gazebo simulation px4 1.14 or later version operation error

### ISSUE THREAD

**Issue by youngjae41** [CopterExpress/clover#491]
Hello I am testing on PX4 latest firmware. It works with some modifications, but I get the following error

WARN [health_and_arming_checks] Preflight Fail: Attitude failure (roll)
WARN [health_and_arming_checks] Preflight Fail: heading estimate not stable
WARN [health_and_arming_checks] Preflight Fail: height estimate error
WARN [health_and_arming_checks] Preflight Fail: Yaw estimate error
WARN [health_and_arming_checks] Preflight Fail: Attitude failure (roll)

**Comment by okalachev** [comment]
We have a beta version of virtual machine image with the simulation built with PX4 v1.13.3, and it seems to work: https://github.com/CopterExpress/clover_vm/releases/tag/v1.4.

So no problem should be with this version, if you install all the software according to the manual.

**Comment by youngjae41** [comment]
@okalachev I'm sorry. I'm testing with the 1.14 beta version of the firmware

**Comment by okalachev** [comment]
I guess it might be a PX4 bug, since it a beta version, not Clover's.

**Comment by youngjae41** [comment]
@okalachev Thank you for your reply. I will test again when realese comes out.

different qustions ..

In order to use aruco marker, is it true that optical flow must be set to true unconditionally?

**Comment by youngjae41** [comment]
PX4 v1.14.0-beta2 testing 

![Screenshot from 2023-06-13 00-49-55](https://github.com/CopterExpress/clover/assets/55374072/3410e503-a6b6-45f5-9df2-851b228ec683)
![Screenshot from 2023-06-13 00-49-58](https://github.com/CopterExpress/clover/assets/55374072/496f5804-bbac-4b19-9c2f-8925ec76e9df)


Modifying the parameters through airframe works, but gyro and imu don't seem to work. In v1.14.0-beta, the existing iris disappeared and was changed to gazebo_iris_classic, but I don't know what the problem is

**Comment by okalachev** [comment]
I would recommend you to switch to stable version of PX4 since I don't see much sense in debugging the beta version for now.

>In order to use aruco marker, is it true that optical flow must be set to true unconditionally?

No, ArUco markers can be used without optical flow.

**Comment by youngjae41** [comment]
@okalachev Ok..

In px4 firmware 1.13.3 version and 1.12.3 version, the aircraft fails to take off when operating after setting optical flow in clover.launch to false.

**Comment by okalachev** [comment]
There might be problems with PX4's estimator to initialize. Is `force_init` argument `true` in `clover.launch`?

Also try to perform `rosrun clover selfcheck.py` when the drone is not working.
