### ISSUE TITLE
No output obtained from sensor on gazebo. Error: Unable to parse message of type[sensor_msg.msgs.Airspeed]

### ISSUE THREAD

**Issue by themboutidem** [CopterExpress/clover#493]
Hi, so I found an airspeed plugin in the sitl_gazebo directory and was using it to make a custom airspeed sensor. 

However, whenever I call it from my .world file, I am met with the following error in the gazebo topic visualizer:
Unable to parse message of type[sensor_msg.msgs.Airspeed]

What can I do to debug why the sensor doesn't work, because there are no other error output. 
<img width="342" alt="Screenshot 2023-08-09 at 4 36 24 PM" src="https://github.com/CopterExpress/clover/assets/86470756/1b43d587-8115-42c0-b4a0-5fc503081311">

**Comment by okalachev** [comment]
Hi! As far as I know, Gazebo client cannot display topics of custom types, unless it was built with support for them. And `sensor_msg.msgs.Airspeed` is a custom topic type.

You may try to print the topic using `gz topic` command line utility. Or, if this air sensor data is passed to the flight controller, you may try to find this data in MAVLink stream using QGroundControl's MAVLink inspector. Or maybe there's mavros topic for that?
