### ISSUE TITLE
Can any one help me please i have problem with connecting remote control ?

### ISSUE THREAD

**Issue by Salehhuwail22** [CopterExpress/clover#494]
I have drone but the remote control it's for another dron and all the drone are same version clover 4.2 can I connect the remote control to my drone and how ?

**Comment by sv4ko** [comment]
hi, if your remote control and receiver work on the same protocol, then they will contact you without any problems. Can you tell me what kind of receiver and remote you have. If the standard one is from the set, then you can take a look at this instruction. https://clover.coex.tech/ru/rc_flysky_a8s.html. You can also write in the telegram channel, if it's more convenient for you https://t.me/COEXHelpdesk
